sudo: required

language:

services:
  - docker

before_install:
  - docker build -t aaroc/code-rade-build-slave:u1404 .
  - docker run -d aaroc/code-rade-build-slave:u1404 /bin/sh -c "echo hi"
  - docker ps -a

script:
