# We need to test :
# Client access to the repositories (for various targets)
# build-slave configuration

# this tests that we can mount and retrieve the version of FastRepo with static mounts

sudo: required

language: ruby
rvm:
  - 2.2
  - 2.3
before_install:
install:
  - cd docs/
  - bundle install
script:
  - jekyll build -c _config-dev.yml

after_success:


after_failure:

notifications:
  slack:
    rooms:
      - africa-arabia-roc:qn956vBmV7VIyJ1Xod4Cmnd5#coderade
