sudo: required

language:

services:
  - docker

before_install:
  - docker build -t aaroc/code-rade-build-slave:u1404 .
  - docker images
  - docker run -d aaroc/code-rade-build-slave:u1404 /bin/sh -c "echo hi"
  - docker ps -a

script:

notifications:
  slack:
    rooms:
      - africa-arabia-roc:qn956vBmV7VIyJ1Xod4Cmnd5#code-rade
