sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t aaroc/code-rade-build-slave:u1404 containers/u1404-buildslave
  - docker images
  - docker run -d aaroc/code-rade-build-slave:u1404 /bin/sh -c "echo hi"
script:
  - docker ps -a


notifications:
  slack:
    rooms:
      - africa-arabia-roc:qn956vBmV7VIyJ1Xod4Cmnd5#coderade
